[tox]
envlist = py{311}-{gha,local}
requires = tox-conda

[testenv]
setenv =
    PYTHONUNBUFFERED = 1
    MPLBACKEND = Agg
deps=
    numpy==2.1.1
    pytest
    setuptools
    wheel
    Cython
    pytest-forked
    pytest-xdist
whitelist_externals = pytest
    /bin/rm
commands =
    gha: pytest -s --log-cli-level=DEBUG --log-cli-format="%(levelname)-8s [%(name)s] %(message)s" --forked -n 1 -v -x sherlockpipe/tests/
    local: pytest -s --log-cli-level=DEBUG --log-cli-format="%(levelname)-8s [%(name)s] %(message)s" --forked -n 1 -v -x sherlockpipe/regression_tests/
